package vexon.sellionpdv.auditoria;

public enum AcaoAuditoria {
    VENDA_CRIADA,
    VENDA_CANCELADA,
    CAIXA_ABERTO,
    CAIXA_FECHADO,
    CAIXA_REFORCO_REGISTRADO,
    CAIXA_SANGRIA_REGISTRADA,
    LANCAMENTO_FINANCEIRO_CRIADO,
    LANCAMENTO_FINANCEIRO_ALTERADO
}
