# Ativado automaticamente pelo Dockerfile via --spring.profiles.active=prod

# Desativa logs de SQL (performance e segurança)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
